/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ITimeline } from "./components/tembici-timeline/tembici-timeline.interface";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TembiciTimeline {
        "initialItem": number;
        "timeline": ITimeline[];
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTembiciTimelineElement extends Components.TembiciTimeline, HTMLStencilElement {
    }
    var HTMLTembiciTimelineElement: {
        prototype: HTMLTembiciTimelineElement;
        new (): HTMLTembiciTimelineElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tembici-timeline": HTMLTembiciTimelineElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TembiciTimeline {
        "initialItem"?: number;
        "onTimelineItemClicked"?: (event: CustomEvent<number>) => void;
        "timeline"?: ITimeline[];
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tembici-timeline": TembiciTimeline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tembici-timeline": LocalJSX.TembiciTimeline & JSXBase.HTMLAttributes<HTMLTembiciTimelineElement>;
        }
    }
}
